FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS base

# Instalar dependências comuns (se necessário)
RUN apk add --no-cache -y \
    git curl unzip \
    && rm -rf /var/lib/apt/lists/*
    
# Definir usuário padrão (opcional, recomendado p/ CI)
RUN useradd -ms /bin/bash runner
USER runner
WORKDIR /home/runner