name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - "dockerfiles/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ "8", "9" ]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/Dockerfile.${{ matrix.version }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hc-dotnet-ci-base:${{ matrix.version }}
            ${{ matrix.version == '9' && format('ghcr.io/{0}/hc-dotnet-ci-base:latest', github.repository_owner) || '' }}
